### ISSUE TITLE
What happened to attached for devices?

### ISSUE THREAD

**Issue by okyeron** [monome/norns#843] opened 2019-06-17 02:43 UTC
Some time back in 1.0 grid and midi devices could be checked if `attached` - Study 4 specifically uses this.

Now I'm searching all the code and can't find it at all. 

What happened here? Did this get tossed for some other better way to determine if a device is connected?

**Comment by artfwo** [comment] 2019-06-17 05:13
Yes, I think I removed that property when cleaning up vport library, you can use `vport.device ~= nil` instead.

**Comment by neauoire** [comment] 2019-06-17 06:28
Could I ask for it to be added back? Not a big fan of `vport.device ~= nil` as replacement.

**Comment by artfwo** [comment] 2019-06-17 06:42
That would be a flag which does nothing but being a duplicate of `vport.device ~= nil`, a potential source of problems if we forget to update it. You can use `vport.device` as a shortcut, which will evaluate to true, if the device is attached.

**Comment by neauoire** [comment] 2019-06-17 06:59
Maybe I'm not exactly sure how to use it then.

```
g = grid.connect()
print(vport) # nil
print(g.vport) # nil
print(grid.vport) # nil
print(norns.vport) # nil
```

**Comment by artfwo** [comment] 2019-06-17 07:17
Right, `grid.connect(x)` returns a vport instance, see https://github.com/monome/norns/blob/master/lua/core/grid.lua#L107

Currently scripts only deal with vports (assigned in devices menu), and we connect to them using `grid.connect`. A vport instance keeps a reference to the physical device, in your example above that would be `g.device`.

Hope this helps!

**Comment by neauoire** [comment] 2019-06-17 07:19
That's actually excellent, sorry for my confusion earlier.

**Closed** 2019-06-18 04:56 UTC
