### ISSUE TITLE
Potential rare bug with clock sync?

### ISSUE THREAD

**Issue by vijaymarupudi** [monome/norns#1803] opened 2024-11-04 20:21 UTC
https://github.com/monome/norns/blob/e8e210ac4b7da320ac80c65ce605bbaccb6e7db8/matron/src/clocks/clock_scheduler.c#L46

I'm curious why the clock sync function uses an epsilon addition before the division instead of after. To me, adding it before the division could cause errors, albeit not so often in practice. Adding it after the division (but before the ceil) makes more sense to me.

For example, if the beat clock is 4 and the requested sync period is also 4, (4 + FLT_EPSILON) / 4 would be equal to 4, making the coroutine run immediately. However, I assume the user would want it to resume on beat clock 8.

Currently the epsilon, as far as I know, only has an effect when the requested sync period is 1, which makes the ceil function provide the next whole integer.

It's entirely possible that I'm missing something here.

**Comment by artfwo** [comment] 2024-11-04 22:47
Yeah, FLT_EPSILON is there by design, to ensure that `sync(x)` after `y` will schedule a resume event at `y+x` if `y` is divisible by `x`.

It works for any sync periods, i.e. sync(0.5) at 4.0 should schedule a resume event at 4.5 and not 4.0, see the following snippet and example output: https://godbolt.org/z/fbT5Mo4ob

The reason that `sync(x)` at `y` beats where `y` is divisible by `x` should be resumed at `(y//x+1)*x` beats is because it can be used in a different scheduler, such as an audio processing callback where sync can be called at a whole (or divisible by `x`) beat the scheduler at exactly `y` beats.

sync(4) at beat 4 should indeed schedule event at 8, adding FLT_EPSILON ensures that too: https://godbolt.org/z/fzvsT3Y5j

So I'm closing this for absence of elements of a bug in the issue :)

**Closed by artfwo** 2024-11-04 22:47 UTC

**Comment by artfwo** [comment] 2024-11-05 07:15
Correct, in division operations epsilon has to be large enough to remain significant. If we're dividing by `N`, for double we'd have to use `(Y + DBL_EPSILON * N) / N` to ensure that the result is greater than `Y / N` and, yes, FLT_EPSILON is just a shortcut :)
