### ISSUE TITLE
Novation Launchpad MK2: MIDI stops working immediately after Launchpad starts up

### ISSUE THREAD

**Issue by neutralinsomniac** [monome/norns#1664] opened 2023-03-19 02:42 UTC
Launchpad seems to work fine on 3 other devices, but on the norns (using midi-monitor) it seems that I'll get maybe a half a second window after the Launchpad boots that midi notes come through, then nothing comes through again until I disconnect and reconnect the Launchpad, at which point the same behavior occurs. I see nothing obvious in dmesg.

**Comment by dndrks** [comment] 2023-03-21 20:01
@neutralinsomniac , hope all's well otherwise!
could you please reproduce the issue and send over [logs](https://monome.org/docs/norns/help/#logs) for the issue to help@monome.org? since [midigrid](https://llllllll.co/t/midigrid-use-launchpads-midi-grid-controllers-with-norns/42336) supports Launchpad MK2 (with confirmed success using the device with norns), I'm curious if there's something else to pursue :)
closing for now, unless we can surface a larger issue

**Closed by dndrks** 2023-03-21 20:01 UTC

**Comment by neutralinsomniac** [comment] 2023-03-25 21:33
do you use a powered usb hub? with only the launchpad plugged into the norns, I get this:
```
[   50.102897] usb 1-1.1: new full-speed USB device number 8 using dwc_otg
[   50.243272] usb 1-1.1: device descriptor read/all, error -32
[   50.342907] usb 1-1.1: new full-speed USB device number 9 using dwc_otg
[   50.473280] usb 1-1.1: device descriptor read/all, error -32
[   50.473562] usb 1-1-port1: attempt power cycle
[   51.132889] usb 1-1.1: new full-speed USB device number 10 using dwc_otg
[   51.163273] usb 1-1.1: device descriptor read/8, error -32
[   51.313279] usb 1-1.1: device descriptor read/8, error -32
[   51.532874] usb 1-1.1: new full-speed USB device number 11 using dwc_otg
[   51.565898] usb 1-1.1: unable to read config index 0 descriptor/all
[   51.565909] usb 1-1.1: can't read configurations, error -71
[   51.566183] usb 1-1-port1: unable to enumerate USB device
10.0.1.149 ~/norns $ 
```

which I usually only see when a device isn't getting enough power over USB.
