### ISSUE TITLE
Latest master wifi connection broken (hotspot fine)

### ISSUE THREAD

**Issue by jlmitch5** [monome/norns#691] opened 2019-01-11 00:47 UTC
With the included dongle, I have not had good luck since updating a couple weeks ago connecting to my home wifi network.  Using norns as a hotspot seems to work fine.

The screen says initiallising wifi... and then eventually status: password fail.  the characters in the password are t*e1N98

The "chosen" network in the bottom does not match the network I had scrolled to for connecting to.

**Comment by catfact** [comment] 2019-01-27 06:40
`dev` branch has totally revamped wifi system using networkl manager. also @ranch-verdin i think has some fixes for the existing wpa_supplicant system on a branch; maybe these should be pulled in to master

**Comment by ranch-verdin** [comment] 2019-01-27 09:17
I fixed a bug which said 'status failed' when router refuses pings. This has already been pulled into master.

However there was regression in the layers beneath wpa_cli some time since the image we were using early 2018 - can only connect once to my home WiFi per reboot. My workaround is to use a different WiFi usb, which works ok (good connection) but not perfect (still some menu glitch, no hotspot). still haven't moved over to dev myself, waiting for the release.

**Comment by jlmitch5** [comment] 2019-01-27 15:54
word, thank y'all for the info.  I am personally fine waiting for dev to land, and I can report back on this issue if I still notice it.  We can close or keep it open, either works for me

**Comment by tehn** [comment] 2019-01-27 19:52
i'm going to close it as 2.0 will use a totally different system (`networkmanager`)

**Closed by tehn** 2019-01-27 19:52 UTC
