### ISSUE TITLE
Screensaver does not always register encoder movement

### ISSUE THREAD

**Issue by antonhornquist** [monome/norns#383] opened 2018-05-29 17:54 UTC
Scripts that do not have all encoders hooked up (ie. the noninteractive script why) will not be restored on encoder movement when screensaver is active. This might be a known issue?

Low priority anyhow...

**Comment by pq** [comment] 2018-06-09 13:58
> Related issue: https://github.com/catfact/norns/issues/314

In the moved repo: #314

Related also to: #414

**Comment by artfwo** [comment] 2018-06-09 14:51
The screensaver timer is currently triggered on `screen.update` and this is actually a duplicate of #314 so I'm closing this.

**Closed by artfwo** 2018-06-09 14:51 UTC
